# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'extendedBuild/pom.xml'
    mavenOptions: '-Xmx1024m'
    publishJUnitResults: 'true'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package sonar:sonar -Dsonar.projectKey=ldeitos_extendedValidation -Dsonar.organization=ldeitos-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6a4235905495fa2093182c65a9c6938502ffb167'    
